### ISSUE TITLE
Protected urls

### ISSUE THREAD

**Issue by jakobeissler** [dsb-norge/vue-keycloak-js#2]
Hello,

Would it be possible to require authentication only on certain routes?

Thanks.

**Comment by nlien** [comment]
Sure. Just use `onLoad: 'check-sso'` as init option, and add a meta property in your router, combined with a router guard:

**main.js**
```
import VueKeyCloak from '@dsb-norge/vue-keycloak-js'
...
Vue.use(VueKeyCloak, {
  init: {
    onLoad: 'check-sso'
  },
  onReady: kc => {
    http.setAuthHeader(kc.token)
    new Vue({
      router,
      created () {
        this.$watch('$keycloak.token', http.setAuthHeader, { immediate: true })
      },
      render: h => h(App)
    }).$mount('#app')
  }
})
```
**routes.js**
```
export default [
  {
    path: '/',
    name: 'main',
    component: Main
  },
  {
    path: '/secured',
    name: 'secured',
    component: Secured,
    meta: {
      requiresAuth: true
    }
  }
]
```
**router.js**

```
import routes from './routes'

const router = new Router({
  routes,
  mode: 'history',
  base: process.env.BASE_URL
})
...
router.beforeEach((to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    if (router.app.$keycloak.authenticated) {
      next()
    } else {
      const loginUrl = router.app.$keycloak.createLoginUrl()
      window.location.replace(loginUrl)
    }
  } else {
    next()
  }
})
```

**Comment by jakobeissler** [comment]
Thank you very much!!!

**Comment by cdecinkoKnight** [comment]
Where is http referenced?

dsb-vue-keycloak.esm.js:165 
        
       Error: Failure during initialization of keycloak-js adapter
    at dsb-vue-keycloak.esm.js:162:23 ReferenceError: http is not defined
    at Object.onReady (keycloak.js?t=1664991809807:38:9)
    at keycloak.onReady (dsb-vue-keycloak.esm.js:130:58)
    at keycloak.js:218:34
